[sys]
    EnableHTTP = true
    HTTPPort = 8023

    EnableHTTPS = false
    HTTPSPort = 10443

    EnableHttpTLS = true
    HTTPSCertFile = "conf/server.crt"
    HTTPSKeyFile = "conf/server.key"
    # 无需手动的调用渲染输出模板
    # autorender = false

    #Session参数
    sessionname = "rmsbackusersessionid"

    #sessioncookielifetime = 100 cookie的有效期（秒），默认是session,即会话结束则过期
    #开启监控
    EnableAdmin = true
    #开启JSON请求
    copyrequestbody = true

    #防止跨站请求伪造 未启用
    enablexsrf = false
    xsrfkey = "asdfioerjlasdfmFADFOEJF2323SDFF"
    xsrfexpire = 3600

[lang]
    types="pt-BR"
    names="Português"

[app]
    appname = "gardens"
    runmode = "dev"
    #runmode = "prod"
    [site]
        app = "p-med"
        name = "Prontuário"
        version = "1.0.15"

[cache]
    redis_host = "127.0.0.1:6379"
    redis_password = ""
    cache_expire = 10   #过期时间
    #tipo de banco de dados：postgres/mysql/sqlite3
    db_type = "mysql"
    #数据库表名前辍
    db_dt_prefix = "rms_"

#sim卡
[simcard]
    api = "http://127.0.0.1:8089/api/Service/QueryCardPackage"
    username = "123213213213"
    key= "1231232131232123213"

[logs]
    #"emergency", "alert", "critical", "error", "warning", "notice", "info", "debug"
    # 0 ~ 7
    level = 7

#postgreSQL配置
[postgres]
    db_alias = "default"
    db_name = "sdrms"
    db_user = "root"
    db_pwd = "root"
    db_host = "localhost"
    db_port = 5432
    db_sslmode = "disable"

#mysql配置
[mysql]
    db_alias = "default"
    db_name = "gardens"
    db_user = "root"
    db_port = 3306
    db_charset = "utf8"
    db_host = "127.0.0.1"
    db_pwd = "root"

#sqlite3配置
#[sqlite3]
#    db_alias = "default"
#    db_name = "sdrms.sqlite3"







